apiVersion: v1
kind: Service
metadata:
  name: whoami-kustomize
  labels:
    app.kubernetes.io/name: whoami-kustomize
spec:
  selector:
    app.kubernetes.io/name: whoami-kustomize
  ports:
    - port: 80
      targetPort: 80
